services:
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - php74
      - php83
      - php84

  php74:
    build:
      context: ./php74
    volumes:
      - ../:/var/www/html
    networks:
      - app-network

  php83:
    build:
      context: ./php83
    volumes:
      - ../:/var/www/html
    networks:
      - app-network

  php84:
    build:
      context: ./php84
    volumes:
      - ../:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
